### ISSUE TITLE
觉得可以增加对图片元数据的索引

### ISSUE THREAD

**Issue by YesHub** [Gaoyongxian666/OpenSearcher#2]
EXIF IPTC XMP三种格式能选择性索引的话,能进一步减小索引

**Comment by Gaoyongxian666** [comment]
python 有能读取图片元数据发的开源库吗？

**Comment by Gaoyongxian666** [comment]
https://github.com/LeoHsiao1/pyexiv2

**Comment by Gaoyongxian666** [comment]
你先用[pyexiv2](https://github.com/LeoHsiao1/pyexiv2)读取一下你自己的图片看能不能读取出信息

**Comment by YesHub** [comment]
> EXIF IPTC XMP

https://blog.csdn.net/qq_35952638/article/details/95088227
试过了可以的，首先图片需要有相关的信息， 然后呢路径如果有中文字符的话需要decode，第二个参数'gbk'

**Comment by YesHub** [comment]
> 你先用[pyexiv2](https://github.com/LeoHsiao1/pyexiv2)读取一下你自己的图片看能不能读取出信息

https://blog.csdn.net/qq_35952638/article/details/95088227
试过了可以的，首先图片需要有相关的信息， 然后呢路径如果有中文字符的话需要decode，第二个参数'gbk'

**Comment by Gaoyongxian666** [comment]
好的，不过这有多少图片类型？

**Comment by YesHub** [comment]
> 好的，不过这有多少图片类型？

格式的话，最好能自定义某种格式， 图片格式太多了。。。

**Comment by YesHub** [comment]
> 好的，不过这有多少图片类型？
类型的话，最好能自定义某种类型， 图片类型太多了。。。
