### ISSUE TITLE
如何移除右键菜单

### ISSUE THREAD

**Issue by newljf** [Gaoyongxian666/OpenSearcher#7]
选上后，右键出现2个菜单，取消后，右键还会有1个菜单，请问如何把右键菜单全部移除。
![微信图片_20221206095313](https://user-images.githubusercontent.com/50931934/205789537-9958687b-61ed-4cf9-b79a-7be228e76c79.jpg)
![微信图片_20221206095318](https://user-images.githubusercontent.com/50931934/205789546-1a3dd804-da15-49b1-84bc-d5438ab6e426.jpg)

**Comment by Gaoyongxian666** [comment]
1.打开注册表
win+r 输入：regedit
2.找到
计算机\HKEY_CLASSES_ROOT\Directory\Background\shell\OpenSearcher
计算机\HKEY_CLASSES_ROOT\Directory\shell\OpenSearcher
3.删除

**Comment by Gaoyongxian666** [comment]
不过你这个键名应该不是我这个OpenSearcher，是你自己起的那个键名

**Comment by Gaoyongxian666** [comment]
还有一种用Python的方式删除，你也是得需要写对键名，要不然删不了

**Comment by Gaoyongxian666** [comment]
这个是我代码出现的漏洞吗

**Comment by Gaoyongxian666** [comment]
按理说我就创建了一次才对

**Comment by Gaoyongxian666** [comment]
按理说我就创建了一次才对
